[package]
name = "rust-knn-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rust_knn_node"

[dependencies]
napi = "2.15.0"
napi-derive = "2.15.0"
rust_knn = "0.1.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true 